version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
